version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A picasso_files worker -l info
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend

  flower:
    build: ./
    command: celery -A picasso_files flower
    volumes:
      - ./:/app
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
